services:
  # frontend:
  #   build: ./peerprep_frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api-gateway
  mongo:
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
  api-gateway:
    env_file:
      - .env
    environment:
      - USER_SERVICE_URL=http://user-service:8000
      - QUESTION_SERVICE_URL=http://question-service:8000
      - MATCHING_SERVICE_URL=http://matching-service:8000
      - QUEUEING_SERVICE_URL=ws://queueing-service:8000
      - SECRET_KEY=CHANGE_ME_TO_ENV_VAR
    build: ./peerprep_backend/api_gateway
    container_name: api-gateway
    depends_on:
      - user-service
      - question-service
      - queueing-service
    ports:
      - "8000:8000"
  user-service:
    depends_on:
      mongo:
        condition: service_healthy
    build: ./peerprep_backend/user_service
    container_name: user-service
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - SECRET_KEY=CHANGE_ME_TO_ENV_VAR
    ports:
      - "8001:8000"

  question-service:
    build: ./peerprep_backend/question_service
    container_name: question-service
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8002:8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Web UI
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  matching-service:
    build: ./peerprep_backend/matching_service
    container_name: matching-service
    depends_on:
      - rabbitmq
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  queueing-service:
    build: ./peerprep_backend/queueing_service
    container_name: queueing-service
    depends_on:
      - rabbitmq
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  chat-service:
    build: ./peerprep_backend/collaboration_service/chat_service
    container_name: chat-service
    ports:
      - "8005:8000"
  
  run-code-service:
    build: ./peerprep_backend/collaboration_service/run_code_service
    container_name: run-code-service
    ports:
      - "8006:8000"