services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
  api-gateway:
    build: ./peerprep_backend/api_gateway
    container_name: api-gateway
    depends_on:
      - user-service
      - question-service
    ports:
      - "8000:8000"
  user-service:
    build: ./peerprep_backend/user_service
    container_name: user-service
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8001:8000"

  question-service:
    build: ./peerprep_backend/question_service
    container_name: question-service
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8002:8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  matching-service:
    build:
      context: ./peerprep_backend/matching_service
    container_name: matching-service
    depends_on:
      - rabbitmq
    ports:
      - "8003:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  queueing-service:
    build:
      context: ./peerprep_backend/queueing_service
    container_name: queueing-service
    depends_on:
      - rabbitmq
    ports:
      - "8004:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
  collaboration-service:
    build: ./peerprep_backend/collaboration_service
    container_name: collaboration-service
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ORIGIN=http://localhost:3000
  yws-service:
    build: ./peerprep_backend/yws_service
    container_name: yws-service
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - HOST=0.0.0.0