services:
  judge0-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    volumes:
      - judge0-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  judge0:
    image: judge0/judge0:latest
    privileged: true
    tmpfs:
      - /box
    environment:
      DATABASE_URL: postgres://judge0:judge0@judge0-db:5432/judge0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT: "false"
      ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT: "false"
    ports:
      - "2359:2358"

  redis:
    image: redis:7-alpine
    container_name: collaboration_service-redis
    ports:
      - "6379:6379"

volumes:
  judge0-db-data:
  judge0-box: